// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace BugTrackerPrompter
{
    internal sealed partial class Vsix
    {
        public const string Id = "BugTrackerPrompter.5f321cb6-f81f-4296-8df6-7b72d0b6ea16";
        public const string Name = "BugTrackerPrompter";
        public const string Description = @"Empty VSIX Project.";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "lsoft";
        public const string Tags = "";
    }
}
